#!/bin/bash
wal -i "$1"
cat ~/.cache/wal/colors.scss | sed s/\\$/@/g > ~/.atom/packages/atom-min-ui/styles/min.less
cat ~/.cache/wal/colors.scss | sed s/\\$/@/g > ~/.atom/packages/min-syntax/styles/colors.less

termcolors -i xresources -o iterm < ~/.cache/wal/colors.Xresources > ~/Themes/iterm/colors/output.itermcolors
node ~/scripts/ui/iterm-update.js
node ~/scripts/ui/ubersicht-update.js

### Set wallpaper
# Using feh to tile the wallpaper now.
# We grab the wallpaper location from wal's cache so 
# that this works even when a directory is passed.
# feh --bg-tile "$(< "${HOME}/.cache/wal/wal")"  

#   Update all Wallpapers
Image = "${HOME}/.cache/wal/wal"
function wallpaper() {
    sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '$1'" && killall Dock 
}
# wallpaper $Image
echo $Image
