name: CV to PDF
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "CV/**.md"
      - ".github/workflows/cv_pdf.yaml"

jobs:
  convert_and_commit_pdf:
    name: Convert MD to PDF and Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: CV/*.md --from markdown --to pdf --output CV/CV.pdf

      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate CV PDF"
          file_pattern: CV/CV.pdf
          branch: master
