name: CV to PDF
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "CV/**.md"
      - ".github/workflows/cv_pdf.yaml"

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: CV
          output_dir: CV
          #           images_dir: docs/images
          #           image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: CV
      - uses: EndBug/add-and-commit@v7
        with:
          add: "CV"
          message: "Generate CV PDF"
          default_author: github_actions
